export enum SymbolFilters {
  MIN_PRICE = "minPrice",
  MAX_PRICE = "maxPrice",
  TICK_SIZE = "tickSize",
  MULTIPLIER_UP = "multiplierUp",
  MULTIPLIER_DOWN = "multiplierDown",
  AVG_PRICE_MINS = "avgPriceMins",
  MIN_QTY = "minQty",
  MAX_QTY = "maxQty",
  STEP_SIZE = "stepSize",
  MIN_NOTIONAL = "minNotional",
  APPLY_TO_MARKET = "applyToMarket",
  LIMIT = "limit",
  MAX_NUM_ORDERS = "maxNumOrders",
  MAX_NUM_ALGO_ORDERS = "maxNumAlgoOrders",
  MAX_NUM_ICEBERG_ORDERS = "maxNumIcebergOrders",
  MAX_POSITION = "maxPosition",
}
